stages:
- name: wikipedia_scraping
  sparql_file: countries.sparql
- name: wikipedia_text_cleaning

- name: corpus_split
  splits:
   - name: train
     proportion: 80
   - name: test
     proportion: 10
   - name: valid
     proportion: 10

- name: corpus_analysis
  corpus_file: train.txt
- name: corpus_analysis
  corpus_file: test.txt
- name: corpus_analysis
  corpus_file: valid.txt
