stages:
- name: fandom_wiki_scraping
  fandom: starwars
  category: Planet_stubs
- name: fandom_wiki_text_cleaning
- name: corpus_split
  splits:
   - name: train
     proportion: 80
   - name: test
     proportion: 10
   - name: valid
     proportion: 10
